---
title: "Closest School Theory - Lat/Long"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
source("helpers.R")
```

## Import relavent files
```{r Import files, include=FALSE}
# Student travel data
student_travel_90 <- readRDS("output/student_travel_0.9.rds")

# School related data
school_sfis_2017 <- readRDS("output/school_sfis_2017.rds") %>%
  rename(year = year.x)
```

## Test closest school theory 

```{r closest school}
student_df <- student_travel_90 %>%
  select(school.name, school.lat, school.long, dsb.index, panel, 
         enrolment, student.postal.code, student.lat, student.long, dist) %>%
  mutate(lat.diff = abs(abs(student.lat) - abs(school.lat)),
         long.diff = abs(abs(student.long) - abs(school.long))) %>%
  mutate(lat.max = student.lat + lat.diff, lat.min = student.lat - lat.diff, 
         long.min = student.long - long.diff, long.max = student.long + long.diff) %>%
  mutate(id.cumsum = cumsum(enrolment)) %>%
  rename(std.school.name = school.name, std.school.long = school.long, std.school.lat = school.lat,
         std.dsb.index = dsb.index, std.panel = panel)

school_df <- school_sfis_2017 %>%
  select(sfis, dsb.index, panel, school.name, school.lat, school.long) 

# For loop through a sample of students
sample_id = sample(1:1629276, 5000, replace=FALSE)
datalist <- list()

for (i in 1:length(sample_id)) {
  student_interest <- student_df %>%
    filter(id.cumsum <= sample_id[i]) %>%
    filter(id.cumsum == max(id.cumsum)) %>%
    mutate(loop.id = i)
  
  LATMAX = student_interest$lat.max
  LATMIN = student_interest$lat.min
  LONGMIN = student_interest$long.min
  LONGMAX = student_interest$long.max

  school_interest <- school_df %>%
    filter(school.lat <= LATMAX, school.lat >= LATMIN, school.long <= LONGMAX, school.long >= LONGMIN) %>%
    mutate(loop.id = i)
  
  closest_school_df <- left_join(school_interest, student_interest, by = "loop.id")
  datalist[[i]] = closest_school_df
}

closest_school_df <- rbindlist(datalist)
write_rds(closest_school_df, 'output/closest_school.rds')
```

```{r summarize results}
closest_school_df %>%
  filter(panel == std.panel) %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.std = n())


closest_elemschool_df <- closest_school_df %>%
  filter(panel == 'Elementary', std.panel == 'Elementary') %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.std = n())


closest_secschool_df <- closest_school_df %>%
  filter(panel == 'Secondary', std.panel == 'Secondary') %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.std = n())

closest_elemschool_df
closest_secschool_df

```

```{r}
#Board Join

dsbindex <- read_csv('input/school_board_types.csv')

closest_school_df <- closest_school_df %>% 
  left_join(dsbindex, by = c('dsb.index' = 'dsb'))
```


```{r}
#Elementary by Board
closest_elemEP_df <- closest_school_df %>%
  filter(panel == 'Elementary', std.panel == 'Elementary', board_type == 1) %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.EPstd = n()) %>% 

closest_elemEC_df <- closest_school_df %>%
  filter(panel == 'Elementary', std.panel == 'Elementary', board_type == 2) %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.ECstd = n())

closest_elemFP_df <- closest_school_df %>%
  filter(panel == 'Elementary', std.panel == 'Elementary', board_type == 3) %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.FPstd = n())

closest_elemFC_df <- closest_school_df %>%
  filter(panel == 'Elementary', std.panel == 'Elementary', board_type == 4) %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.FCstd = n())

#Join Tables
closest.english.elem_df <- full_join(closest_elemEP_df, closest_elemEC_df, by=c("n.schools"))
closest.french.elem_df <- full_join(closest_elemFP_df, closest_elemFC_df, by=c("n.schools"))
closest.allelem_df <- full_join(closest.english.elem_df, closest.french.elem_df, by=c("n.schools"))

```

```{r}
#Secondary by Board

closest_secEP_df <- closest_school_df %>%
  filter(panel == 'Secondary', std.panel == 'Secondary', board_type == 1) %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.EPstd = n())
  

closest_secEC_df <- closest_school_df %>%
  filter(panel == 'Secondary', std.panel == 'Secondary', board_type == 2) %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.ECstd = n())

closest_secFP_df <- closest_school_df %>%
  filter(panel == 'Secondary', std.panel == 'Secondary', board_type == 3) %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.FPstd = n())

closest_secFC_df <- closest_school_df %>%
  filter(panel == 'Secondary', std.panel == 'Secondary', board_type == 4) %>%
  group_by(loop.id) %>%
  summarise(n.schools = n()) %>%
  group_by(n.schools) %>%
  summarise(number.of.FCstd = n())

#Join Tables
closest.english.sec_df <- full_join(closest_secEP_df, closest_secEC_df, by=c("n.schools"))
closest.french.sec_df <- full_join(closest_secFP_df, closest_secFC_df, by=c("n.schools"))
closest.allsec_df <- full_join(closest.english.sec_df, closest.french.sec_df, by=c("n.schools"))

```


```{r}
ggplot(closest_elemEC_df, aes(x=n.schools, y=number.of.std)) + geom_bar(stat = "identity")


```













